import re
from datetime import datetime, timezone

import numpy as np
import pandas as pd
import structlog
from astropy import units as u
from astropy.coordinates import SkyCoord
from astropy.time import Time
from skyfield.api import load, wgs84
from skyfield.data import mpc
from structlog.types import FilteringBoundLogger
from tqdm import tqdm

from sotrplib.maps.core import ProcessableMap
from sotrplib.sources.sources import RegisteredSource


def create_observer(
    lat: u.Quantity[u.deg] = -22.96098 * u.deg,
    lon: u.Quantity[u.deg] = -67.7876 * u.deg,
    elev: u.Quantity[u.m] = 5180 * u.m,
) -> wgs84.latlon:
    """Create a Skyfield observer for the Simons Observatory LAT site."""
    return wgs84.latlon(
        lat.to_value(u.deg), lon.to_value(u.deg), elevation_m=elev.to_value(u.m)
    )


## need to normalize the names in Paul's file to the MPC format
## warning! this doesn't work with comets (probably fine, but we wont have comet ephemerides)
def normalize_asteroid_name(name: str) -> str:
    """
    Convert asteroid names such as:
        '3552 Don Quixote (1983 SA)' → '(3552) Don Quixote'
        '7335 (1989 JA)'             → '(7335) 1989 JA'
    """
    # Extract leading number and the rest
    m = re.match(r"^\s*(\d+)\s*(.*)$", name)
    if not m:
        return name  # fallback if pattern is unexpected

    number, rest = m.groups()

    # Extract provisional designation at end e.g. (1991 CS)
    provisional = None
    m2 = re.search(r"\(([^)]+)\)\s*$", rest)
    if m2:
        provisional = m2.group(1)
        rest = rest[: m2.start()].strip()  # remove the parentheses section

    # Determine final name
    if rest:  # there's a real name
        final_name = rest
    else:  # no real name -> use the provisional designation
        final_name = provisional if provisional else ""

    if final_name:
        return f"({number}) {final_name}"
    else:
        return f"({number})"


def generate_mpc_orbital_database(
    mpcorb_dat_file,
    asteroid_flux_estimates_file: str = "solar_system_objects.txt",
    output: str = "mpc_orbital_params_bright_asteroids.csv",
    flux_min: u.Quantity[u.mJy] = 10 * u.mJy,
    log: FilteringBoundLogger | None = None,
):
    """
    MPC orb catalog from https://www.minorplanetcenter.net/iau/MPCORB.html
    Asteroid flux estimates from Paul Chichura, SPT. estimated at 150 GHz at closest approach to Earth.
    """
    log = log or structlog.get_logger()
    log = log.bind(function="solar_system.generate_mpc_orbital_database")
    sso_name, _, _, maxflux = np.loadtxt(
        asteroid_flux_estimates_file, delimiter="\t", dtype="str", unpack=True
    )
    maxflux = np.asarray(maxflux, dtype=float) * u.mJy
    bright_sso_names = []
    for i in range(len(sso_name)):
        if (
            (maxflux[i] > flux_min)
            & (~sso_name[i].startswith("C"))
            & (~sso_name[i].startswith("("))
        ):
            bright_sso_names.append(sso_name[i])
    log.info(
        "solar_system.generate_mpc_orbital_database.sso_estimates_loaded",
        n_bright_asterids=len(bright_sso_names),
        flux_min=flux_min.to_value(u.mJy),
        flux_units=str(flux_min.unit),
    )

    with load.open(mpcorb_dat_file) as f:
        minor_planets = mpc.load_mpcorb_dataframe(f)

    log.info(
        "solar_system.generate_mpc_orbital_database.mpcorb_loaded",
        n_minor_planets=len(minor_planets),
    )

    # Filtering the orbits dataframe to avoid triggering
    # an `EphemerisRangeError` on ill-defined orbits.
    bad_orbits = minor_planets.semimajor_axis_au.isnull()
    minor_planets = minor_planets[~bad_orbits]

    ## get mpc file designations and compare to our bright sso names
    mpc_file_des = set(minor_planets.designation.values)
    new_db = []
    for name in tqdm(bright_sso_names, desc="Generating MPC orbital database"):
        des = normalize_asteroid_name(name)
        # Skip if designation is not in the MPC table
        if des not in mpc_file_des:
            continue
        # Append the row as a dict or Series
        row = minor_planets.loc[minor_planets.designation == des].iloc[0]
        new_db.append(row)
    new_db_df = pd.DataFrame(new_db)
    new_db_df.to_csv(output, index=False)
    log.info(
        "solar_system.generate_mpc_orbital_database.database_generated",
        output_file=output,
        n_asteroids=len(new_db_df),
    )

    return


def load_mpc_orbital_database(
    mpc_database_path: str = "mpc_orbital_params_bright_asteroids.csv",
):
    """Load the MPC orbital database from the specified path.
    This takes the CSV file generated by sotrplib.solar_system.generate_mpc_orbital_database
    """
    df = pd.read_csv(mpc_database_path, dtype=str)

    ## convert to floats where possible. needed for skyfield
    for col in df.columns:
        try:
            df[col] = pd.to_numeric(df[col], errors="raise")
        except ValueError:
            pass

    return df


def interpolate_ephem(
    obj_df,
    target_jd: list[float] | float,
    window: u.Quantity = 0.5 * u.day,
    log: FilteringBoundLogger | None = None,
) -> np.ndarray:
    """
    obj_df : pandas db
     database of ephemerides for an asteroid.
     must contain columns 'julian_day', 'ra_deg', 'dec_deg'
    target_jd : list | float
     Julian dates of desired times at which to interpolate.
    window : u.Quantity
     Days around target to include in spline interpolation
    log: FilteringBoundLogger
        Logger for logging information, by default None.

    Returns: array of shape len(target_jd) with interpolated position
        as SkyCoord objects.


    expects ephemerides to be sampled such that there are at least 4 points within
    +- window of each target_jd for the spline interpolation to work.
    If not, it will return NaNs for that target_jd and print a warning.

    """
    from scipy.interpolate import UnivariateSpline

    log = log or structlog.get_logger()

    target_jd = np.atleast_1d(target_jd)

    if min(obj_df["julian_day"]) > max(target_jd) or max(obj_df["julian_day"]) < min(
        target_jd
    ):
        log.error(
            "interpolate_ephem.no_target_jd_in_range",
            target_jd_range=(min(target_jd), max(target_jd)),
            ephem_jd_range=(obj_df["julian_day"].min(), obj_df["julian_day"].max()),
        )
        return np.full((len(target_jd), 2), np.nan)

    if (
        min(target_jd) < obj_df["julian_day"].min()
        or max(target_jd) > obj_df["julian_day"].max()
    ):
        log.warn(
            "interpolate_ephem.some_target_jd_out_of_range",
            target_jd_range=(min(target_jd), max(target_jd)),
            ephem_jd_range=(obj_df["julian_day"].min(), obj_df["julian_day"].max()),
        )

    results = []
    for tjd in target_jd:
        subset = obj_df[np.abs(obj_df["julian_day"] - tjd) < window]

        if len(subset) < 4:
            results.append(
                SkyCoord(ra=np.nan * u.deg, dec=np.nan * u.deg, frame="icrs")
            )
            log.warn(
                "interpolate_ephem.too_few_interpolation_points",
                target_jd=tjd,
                n_points=len(subset),
                window=window.to_value(u.day),
            )
            continue

        t = subset["julian_day"].values
        ra = subset["ra_deg"].values
        dec = subset["dec_deg"].values

        ra_spline = UnivariateSpline(t, ra, k=3, s=0)
        dec_spline = UnivariateSpline(t, dec, k=3, s=0)

        ra_i = ra_spline(tjd)
        dec_i = dec_spline(tjd)

        results.append(SkyCoord(ra=ra_i * u.deg, dec=dec_i * u.deg, frame="icrs"))

    return np.array(results)


def get_sso_ephem_at_time(
    ephem_df: pd.DataFrame,
    sample_times: list | float,
    interp_time_range: u.Quantity = 0.5 * u.day,
    log: FilteringBoundLogger | None = None,
) -> list[RegisteredSource]:
    """
    Get sso ephemeris positions at time(s) sample_times

    """
    return


def get_sso_ephem_in_map(
    input_map: ProcessableMap,
    ephem_df: pd.DataFrame,
    return_nearest: bool = True,
    interp_time_range: u.Quantity = 0.5 * u.day,
    interp_to: u.Quantity | None = 10 * u.min,
    log: FilteringBoundLogger | None = None,
) -> list[RegisteredSource]:
    """Get solar system objects that fall within the provided map.

    Parameters
    ----------
    input_map : ProcessableMap
        Map to check for solar system objects.
    ephem_df : pd.DataFrame
        DataFrame containing ephemerides of solar system objects.
    return_nearest : bool, optional
        Whether to return the nearest ephemeris point, by default True.
    interp_time_range : u.Quantity, optional
        Time range for interpolation, by default +- 0.5*u.day
    interp_to: u.Quantity, optional
        Interpolation sample rate for detecting if an asteroid is in the map.
    log : FilteringBoundLogger, optional
        Logger for logging information, by default None.

    Returns
    -------
    sso_ephems : dict
        Dictionary mapping object designations to their ephemerides .
    """
    time_range = [
        np.amin(input_map.time_first[input_map.time_first > 0]),
        np.nanmean(input_map.time_mean[input_map.time_first > 0]),
        np.nanmax(input_map.time_last),
    ]
    time_jd = Time(time_range, format="unix", scale="utc").jd
    if interp_to is not None:
        time_jd = np.arange(
            np.min(time_jd), np.nanmax(time_jd), interp_to.to_value(u.day)
        )

    sso_ephems = {}
    unique_objs = ephem_df["designation"].unique()
    for obj in unique_objs:
        obj_df = ephem_df[ephem_df["designation"] == obj]
        interp_pos = interpolate_ephem(obj_df, time_jd)

        y, x = input_map.flux.wcs.world_to_pixel(interp_pos)
        nx, ny = input_map.flux.shape
        x, y = np.round(x).astype(int), np.round(y).astype(int)
        inside = (x >= 0) & (y >= 0) & (x < nx) & (y < ny)
        result = np.zeros_like(x, dtype=bool)
        result[inside] = np.nan_to_num(input_map.flux[x[inside], y[inside]]).astype(
            bool
        )
        if not np.any(result):
            continue

        mean_pos = SkyCoord(
            ra=np.mean(interp_pos.ra[result]),
            dec=np.mean(interp_pos.dec[result]),
        )
        map_time_at_mean_pos = input_map.time_mean.at(
            [mean_pos.dec.to_value("rad"), mean_pos.ra.to_value("rad")]
        )
        nearest_pos = interpolate_ephem(
            obj_df, Time([map_time_at_mean_pos], format="unix", scale="utc").jd
        )

        sso_ephems[obj] = {
            "pos": nearest_pos,
            "time": datetime.fromtimestamp(map_time_at_mean_pos, tz=timezone.utc),
        }

    return sso_ephems
